name: biomed_application
description: A new Flutter project

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0   # versi terbaru


flutter:
  uses-material-design: true
  assets:
    - assets/images/
